export * from './normalizeStringForCompare'
export * from './removeArabicCharacters'
export * from './removeArabicCharactersFromObject'
export * from './removeArabicNumbers'
export * from './removeWhitespaces'
export * from './stringTools'